### PR TITLE
Fix for errors with formatting verbs.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by davecheney** [comment]
I'm sorry this package is not under development. It will be deleted.

**Comment by ncw** [comment]
Are you still planning to delete this package after talking about it in http://dave.cheney.net/paste/gocon-spring-2016.pdf ?

I think it is great and I love its razor focus as compared to https://godoc.org/github.com/juju/errgo

**Comment by davecheney** [comment]
No, I will address this issue and close it.

**Comment by davecheney** [comment]
Thank you for this change, sadly it has been replaced by #2 so I will close this PR

**Pull request closed without merging**
